import Head from 'next/head'
import Conversions from '../components/Conversions'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* side bar... */}
      <Sidebar />
      {/* Main ... */}
      <Conversions />
    </div>
  )
}
