import Head from 'next/head'
import Conversations from '../components/Conversations'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* main */}
      <div className='flex'>
        {/* side bar... */}
        <Sidebar />
        {/* Main ... */}
        <Conversations />
      </div>
    </div>
  )
}
